apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pipaflow-headers
  namespace: pipaflow
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "strict-origin-when-cross-origin"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipaflow
  namespace: pipaflow
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: pipaflow-pipaflow-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pipaflow.nexti.ro
      secretName: pipaflow-tls
  rules:
    - host: pipaflow.nexti.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pipaflow
                port:
                  number: 80
